id: P467B1BED
initial_creation_type: input
source_metadata:
  title: Dying and the Bardos
  language: fr
  description: 'Lotsawa House presents the following texts as part of our Dying and
    Bardos Series:'
  volume:
    3da5aedf5a9f43e8a499ef1d617f7b76:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Dying
    ef7cf68836f64eddbe57aa1c4ef1e338:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Dying
    f1b5e03715974d7c9bb7228d5c165295:
      title: Advice for Hor Özer
      parent: Dying
    587c7ff64ca84062acf20135e89bacdb:
      title: Advice for a Dying Practitioner
      parent: Dying
    2fa4d77ee9ce4556a1db50086fe4bd2f:
      title: Aspiration at the Moment of Death
      parent: Dying
    9c2f9e71cc704671a8bdaf11f0585cae:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Dying
    9d6fe88ba98f4ee78dd7d543e2bfd205:
      title: A Wondrous Instruction for the Moment of Death
      parent: Dying
    b569984ea15046db8225280056adea1d:
      title: Meditation on Amitābha
      parent: Dying
    a7aaac4af3f94a3cbe9fe72c7a25d687:
      title: The Root Verses on the Six Bardos
      parent: Bardos
    766e303fd0d44c7196099a00ec9d6bef:
      title: 'Crucial Advice: A Complete Set of Instructions for the Bardos'
      parent: Bardos
    5a8bf75d56454dc197a895307a6c8807:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Bardos
    53864811ac6d4eddb554ba011027bd03:
      title: A Brief Introduction to the Bardos
      parent: Bardos
    2af838059fd5420c90c113ab6900d9e9:
      title: 'Fostering Recollection to Dispel the Torment of Deluded Perception:
        An Aspiration for the Bardos'
      parent: Prayers
    e2a3c841335448c888f1611cc5076cf8:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Prayers
    68925f0a377c40d8822c7522bf8ef31f:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Prayers
    cc7ff9ea1f514e8b97df489474f8c6a6:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
created_at: '2022-03-01T03:30:40.704293'
last_modified_at: '2022-03-01T03:30:40.704296'
